- name: deploy ArtStyle web application
  hosts: artstyle_nodes
  tasks:
  - name: Copy files to remote server
    copy:
      src: "{{ item }}"
      dest: "~/artstyle/"
    loop:
      - artstyle-client.tar.gz
      - artstyle-server.tar.gz
      - .env
      - artstyle_nodes.ini
  
  - name: extract gz files
    shell: "gzip -fd artstyle-server.tar.gz artstyle-client.tar.gz"
    args:
      chdir: "~/artstyle/"
      warn: false

  - name: load client image
    shell: docker load -i artstyle-client.tar
    args:
      chdir: "~/artstyle/"

  - name: load server image
    shell: docker load -i artstyle-server.tar
    args:
      chdir: "~/artstyle/"
  
  - name: run application containers
    shell: docker compose -f docker-compose.yml up -d
    args:
      chdir: "~/artstyle/"